version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork  # 동일한 네트워크 명을 사용

  health_genie:
    image: ${{secret.DOCKER_USERNAME}}/health_genie
    environment:
      - SPRING_REDIS_HOST=redis  # Redis 서비스의 이름을 사용
    ports:
      - "8080:1234"
    depends_on:
      - redis
    networks:
      - mynetwork  # 동일한 네트워크 명을 사용

networks:
  mynetwork: