
server:
  port: 1234
  error:
    include-message: always
    include-binding-errors : always

# live server
devtools:
  livereload:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/health_genie
    username : root
    password : vvxc9874
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl : false
        format_sql: true
    database: mysql
  mail:
    # stmp.gmail.com -> 587 port number
    host: smtp.gmail.com
    port: 587
    username:
    # spring.mail.password= password -> myaccount.google.com
    password:
    properties:
      mail:
        default-encoding : utf-8
        #debug : true # for developing
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# for encode of password
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# hibernate logging
logging:
  level:
    org:
      springframework:
        security: DEBUG