server:
  port: 1234
  error:
    include-message: always
    include-binding-errors : always

# live server
devtools:
  livereload:
    enabled: true

spring:
  profiles:
    default: dev # 기본 환경을 dev 로

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/health_genie
#    username : root
#    password : vvxc9874
    username : ENC(nAsqvWCx8AVbIHeRZ7uY3w==)
    password : ENC(YO1qfrCAV02aYQYHJupxJAePvy8bzqkE)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl : false
        format_sql: true
    database: mysql

  mail:
    # stmp.gmail.com -> 587 port number
    host: smtp.gmail.com
    port: 587
    username : jeaun8061@gmail.com
    password : vvxc9874
#    username: ENC(NqNmjGbZOQfimoMI2BXagz+zMKbxZiP1)
    # spring.mail.password= password -> myaccount.google.com
#    password: ENC(etHNO+7HUizMoFYexGWYKcuYYXGfkR1dRIock26/oS8=)
    properties:
      mail:
        default-encoding : utf-8
        #debug : true # for developing
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# for encode of password
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# hibernate logging
logging:
  level:
    org:
      springframework:
        security: DEBUG

social:
  kakao:
    client-id: c8d5676bf2406c1c8d922ff01e72f0c9
    redirect: /auth/kakao/redirect
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink
      base: http://localhost:1234